export const COLOR_SEMANTIC_LABEL_NEUTRAL = '#70737C';
export const COLOR_ATOMIC_HOTPINK_70 = '#F86885';
export const COLOR_SEMANTIC_PRIMARY_NORMAL = '#FD7A19';
export const COLOR_SEMANTIC_FILL_NORMAL = '#F4F4F5';
export const COLOR_ATOMIC_ORANGE_80 = '#FEAF75';
export const COLOR_ATOMIC_ORANGE_95 = '#FFE4D1';
export const COLOR_SEMANTIC_LABEL_NORMAL = '#292A2D';

export const COLOR_SEMANTIC_PRIMARY_DARK = '#E76D00';
